version: '3.8'

services:
   django: &django
      build:
         context: .
         target: django
      command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
      volumes:
         - backend:/backend
      ports:
         - 8000:8000
      depends_on:
         - postgres
         - redis
      networks:
         - default
      env_file:
         - .env.local

   postgres:
      image: postgres:latest
      restart: always
      volumes:
         - postgres:/var/lib/postgresql/data
         - archive:/var/lib/postgresql/archive
      networks:
         - default
      ports:
         - 5432:5432
      env_file:
         - .env.local

   nextjs:
      build:
         context: .
         target: nextjs
      networks:
         - default
      command: 'npm run start'
      restart: always
      ports:
         - 3000:3000

   redis:
      image: redis:latest
      networks:
         - default
      restart: always

   celery:
      build:
         context: .
         target: django
      depends_on:
         - django
      volumes:
         - backend:/backend
      command: 'celery -A conf worker --loglevel=info'
      env_file:
         - .env.local

   beat:
      build:
         context: .
         target: django
      depends_on:
         - django
      volumes:
         - backend:/backend
      command: 'celery -A conf beat --loglevel=info'
      env_file:
         - .env.local

   flower:
      build:
         context: .
         target: django
      volumes:
         - backend:/backend
      depends_on:
         - django
      command: 'celery -A conf flower --basic_auth=user:user123456'
      environment:
         - VIRTUAL_HOST=${FLOWER_HOST}
         - VIRTUAL_PORT=5555
      ports:
         - 5555:5555
      env_file:
         - .env.local

volumes:
  postgres:
  backend:
  archive:
