# Generated by Django 3.2.9 on 2021-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nezbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='patronymic name'),
        ),
    ]
