# Generated by Django 3.2.9 on 2021-12-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nezbank', '0002_user_patronymic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_status',
            field=models.CharField(choices=[('not_verified', 'Не верифицирован'), ('email_sent', 'Письмо с подтверждением отправлено'), ('verified', 'Верифицирован')], default='not_verified', max_length=32, verbose_name='Статус email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
    ]
