# Generated by Django 3.2.9 on 2022-01-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django_celery_beat.models import PeriodicTask, CrontabSchedule


def add_task(apps, schema_editor):
    PeriodicTask.objects.create(
        name='update actual currency',
        task='nezbank.tasks.check_currency',
        crontab=CrontabSchedule.objects.get_or_create(
            minute='0',
            hour='2',
            day_of_week='*',
            day_of_month='*',
            month_of_year='*',
            timezone='Europe/Moscow',
        )[0],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('nezbank', '0003_auto_20211231_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
        migrations.RunPython(
            add_task,
            reverse_code=migrations.RunPython.noop
        ),
    ]
