# Generated by Django 3.2.9 on 2021-12-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nezbank', '0002_auto_20211228_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средств на счете'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='currency',
            field=models.CharField(max_length=50, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс'),
        ),
    ]
